### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by andresrsanchez** [ardliath/DeepSpace#50]
Hello,

I have readed the README to contribute to this project and i don't understand how this project works, i mean, i fork the project, clone and run and i dont get it.
Some documentation or first steps would be appreciated.
Thanks!

**Comment by ardliath** [comment]
Hi Andre

Yep, I was working on exactly that this lunchtime!

This started as a project to help me learn Azure and Cosmos/DB so it's designed to work there. I created a very rough How To guide here: https://github.com/ardliath/DeepSpace/wiki/Installation but it's not nearly as detailed as I'd like yet. I've also opened my own question to ask if there's a need for this to work with other database technologies to avoid forcing people into azure.

The basic concept is that this is a UI less game. In other words it's an API sitting on top of a cosmos DB database. Developers/Players call the API to create a ship, move it around, and use it to attack other ships. It is therefore down to the developer to decide if they want to add a UI, or if they want to implement some kind of AI to control their ships.

Documentation is coming, I have to admit I wasn't expecting people to want to contribute for a little bit yet and my code got ahead of my documentation! Is there anything else you'd like to know?

Adam

**Comment by ardliath** [comment]
You could also take a look at this repository: https://github.com/ardliath/DeepSpace.client

This is the work in progress to create a .NET client to call the api and the beginnings of my own AI

Adam

**Comment by andresrsanchez** [comment]
Oh i didn't see the Installation file, my fault!
Now i'm going to explore the project a little bit.
Thanks!

**Comment by ardliath** [comment]
No problem, it most likely wasn't there when you first looked!

Do give me a shout if you have any other questions, it would be great to have you involved!

Adam
